/obj/item/ammo_magazine/speedloader
/obj/item/ammo_magazine/speedloader/rubber
/obj/item/ammo_magazine/speedloader/magnum
/obj/item/ammo_magazine/speedloader/small
/obj/item/ammo_magazine/speedloader/clip
/obj/item/ammo_magazine/shotholder
/obj/item/ammo_magazine/shotholder/on_update_icon()
/obj/item/ammo_magazine/shotholder/attack_hand(mob/user)
/obj/item/ammo_magazine/shotholder/shell
/obj/item/ammo_magazine/shotholder/beanbag
/obj/item/ammo_magazine/shotholder/flash
/obj/item/ammo_magazine/shotholder/stun
/obj/item/ammo_magazine/shotholder/empty
/obj/item/ammo_magazine/machine_pistol
/obj/item/ammo_magazine/machine_pistol/empty
/obj/item/ammo_magazine/smg_top
/obj/item/ammo_magazine/smg_top/empty
/obj/item/ammo_magazine/smg_top/rubber
/obj/item/ammo_magazine/smg_top/practice
/obj/item/ammo_magazine/smg
/obj/item/ammo_magazine/smg/empty
/obj/item/ammo_magazine/pistol
/obj/item/ammo_magazine/pistol/empty
/obj/item/ammo_magazine/pistol/rubber
/obj/item/ammo_magazine/pistol/double
/obj/item/ammo_magazine/pistol/double/rubber
/obj/item/ammo_magazine/pistol/double/practice
/obj/item/ammo_magazine/pistol/small
/obj/item/ammo_magazine/pistol/small/empty
/obj/item/ammo_magazine/magnum
/obj/item/ammo_magazine/magnum/empty
/obj/item/ammo_magazine/box/smallpistol
/obj/item/ammo_magazine/box/pistol
/obj/item/ammo_magazine/box/pistol/empty
/obj/item/ammo_magazine/pistol/throwback
/obj/item/ammo_magazine/box/emp/pistol
/obj/item/ammo_magazine/box/emp/smallpistol
/obj/item/ammo_magazine/proto_smg
/obj/item/ammo_magazine/gyrojet
/obj/item/ammo_magazine/gyrojet/empty
/obj/item/ammo_magazine/box/machinegun
/obj/item/ammo_magazine/box/machinegun/empty
/obj/item/ammo_magazine/rifle
/obj/item/ammo_magazine/mil_rifle
/obj/item/ammo_magazine/mil_rifle/empty
/obj/item/ammo_magazine/mil_rifle/practice
/obj/item/ammo_magazine/caps
