/obj/item/ammo_casing/pistol
/obj/item/ammo_casing/pistol/rubber
/obj/item/ammo_casing/pistol/practice
/obj/item/ammo_casing/pistol/small
/obj/item/ammo_casing/pistol/small/rubber
/obj/item/ammo_casing/pistol/small/practice
/obj/item/ammo_casing/pistol/magnum
/obj/item/ammo_casing/pistol/throwback
/obj/item/ammo_casing/gyrojet
/obj/item/ammo_casing/flechette
/obj/item/ammo_casing/shotgun
/obj/item/ammo_casing/shotgun/pellet
/obj/item/ammo_casing/shotgun/blank
/obj/item/ammo_casing/shotgun/practice
/obj/item/ammo_casing/shotgun/beanbag
/obj/item/ammo_casing/shotgun/stunshell
/obj/item/ammo_casing/shotgun/stunshell/emp_act(severity)
/obj/item/ammo_casing/shotgun/flash
/obj/item/ammo_casing/rifle
/obj/item/ammo_casing/shell
/obj/item/ammo_casing/shell/apds
/obj/item/ammo_casing/rifle/military
/obj/item/ammo_casing/rifle/military/practice
/obj/item/ammo_casing/rocket
/obj/item/ammo_casing/cap
/obj/item/ammo_casing/pistol/emp
/obj/item/ammo_casing/pistol/small/emp
/obj/item/ammo_casing/shotgun/emp
